name: saveuz-deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy backend
        run: |
          set -e

          cd /var/www/saveuz

          echo "ğŸ“¥ Pulling code"
          git pull origin main

          echo "ğŸ Activate venv"
          source venv/bin/activate

          echo "ğŸ“¦ Install requirements"
          pip install -r requirements.txt

          echo "ğŸ§± Migrations"
          python manage.py migrate --noinput

          echo "ğŸ¨ Collect static"
          python manage.py collectstatic --noinput

          echo "ğŸ” Restart supervisor"
          supervisorctl restart saveuz

          echo "âœ… Deploy finished"
